kind: pipeline
name: test

steps:
- name: black
  image: cytopia/black:latest-0.2
  commands:
  - black --check .

- name: flake8
  image: alpine/flake8:3.7.7
  commands:
  - flake8

- name: test
  depends_on:
  - flake8
  image: vmck/vagrant-vmck:0.3.0
  commands:
  - export VMCK_URL=http://$VMCK_IP:$VMCK_PORT
  - export VMCK_NAME="drone $DRONE_REPO:$DRONE_BRANCH#$DRONE_BUILD_NUMBER"
  - export SHUTDOWN=15
  - ci/deploy-vmck

---
kind: pipeline
name: publish

trigger:
  status:
  - success
  event:
  - push
  - tag

depends_on:
- test

steps:
- name: docker push branch ${DRONE_COMMIT_BRANCH}
  image: plugins/docker
  settings:
    repo: vmck/vmck
    tags: ${DRONE_COMMIT_BRANCH}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push

- name: docker push autotag + latest
  image: plugins/docker
  settings:
    repo: vmck/vmck
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
