# Generated by Django 2.1.7 on 2019-04-19 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
                ('data', models.BinaryField()),
                ('job', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='vmck.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
            ],
        ),
    ]
