# Generated by Django 2.2.1 on 2019-05-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmck', '0002_source_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='job',
        ),
        migrations.RemoveField(
            model_name='source',
            name='job',
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.DeleteModel(
            name='Artifact',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
