# Generated by Django 2.2.4 on 2019-08-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmck', '0004_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='token',
            field=models.CharField(default='none', max_length=128),
        ),
    ]
