# Generated by Django 3.0.8 on 2020-09-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmck', '0004_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='backend',
            field=models.CharField(choices=[('qemu', ''), ('raw_qemu', '')], default='qemu', max_length=32),
        ),
    ]
