# Generated by Django 2.2.4 on 2019-08-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmck', '0004_job_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(default='default', max_length=32),
        ),
    ]
