#!/usr/bin/env bash

cd "$( dirname "${BASH_SOURCE[0]}" )"

function clean {
    vagrant destroy -f || echo "vagrant destroy failed, but we don't care"
}
trap clean  EXIT

set -ex

vagrant up

vagrant ssh <<'EOF'
set -e
bash /opt/vmck/ci/test-pytest.sh
bash /opt/vmck/ci/test-alive-on-cluster.sh
EOF
