# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'etc'

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
if Vagrant.has_plugin?('vagrant-env')
    config.env.enable
  end

  machine_name = ENV['MACHINE_NAME'] || ("liquid-vagrant-" + `hostname`.strip)
  custom_sh = ENV['PROVISION_SH']

  config.vm.define machine_name
  # disable implicit mount for /vagrant
  config.vm.synced_folder '.', '/vagrant', disabled: true

  # blank provisioner that can be overridden by providers
  config.vm.provision 'provider', type: 'shell', inline: '/bin/true', privileged: false

  config.vm.network :forwarded_port, guest: 80  , guest_ip: "10.66.60.1", host: 1380,  host_ip: "127.0.0.1"
  config.vm.network :forwarded_port, guest: 4646, guest_ip: "10.66.60.1", host: 14646, host_ip: "127.0.0.1"
  config.vm.network :forwarded_port, guest: 8500, guest_ip: "10.66.60.1", host: 18500, host_ip: "127.0.0.1"
  config.vm.network :forwarded_port, guest: 8200, guest_ip: "10.66.60.1", host: 18200, host_ip: "127.0.0.1"

  config.vm.provider :vmck do |vmck, override|
    vmck.vmck_url = ENV['VMCK_URL']
    vmck.memory = 1024 * 4
    vmck.cpus = 2

    override.vm.box = "base"
    override.nfs.functional = false
    override.vm.provision(
      'provider',
      preserve_order: true,
      type: 'shell',
      path: "wait-cluster.sh",
      inline: nil,
      privileged: false,
    )
    override.vm.synced_folder "../.", "/opt/node", type: "rsync",
      rsync__exclude: [".vagrant/", ".git/", "__pycache__/",
                       "venv/", "volumes/", "collections/"]
  end
end
